name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants write access for pushing to gh-pages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Sass
        run: npm install --save-dev sass
      - name: Compile SCSS to CSS
        run: |
          npx sass style.scss style.css || exit 1
          ls -la  # Log files for debugging
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Deploys from root; adjust to 'Travel-Website' if needed
          keep_files: false  # Ensures clean deployment
          destination_dir: Travel-Website  # Aligns with URL structure
